<?php
/*
 *  @copyright (c) 2023.
 *  @author     Alan Fuller (support@fullworksplugins.com)
 *  @licence    GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 *  @link       https://fullworksplugins.com
 *
 *  This file is part of a Fullworks' Plugin.
 *
 *  This WordPress plugin  is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This WordPress plugin  is  distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  Any copying of any part of this code not in compliance with the licence terms is strictly prohibited.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with the plugin.  https://www.gnu.org/licenses/gpl-3.0.en.html
 */

namespace Fullworks_Vulnerability_Scanner\Includes;


/**
 * Class Audit_Email
 * @package Fullworks_Vulnerability_Scanner\Includes
 */
class Audit_Email {

	/** @var Event_Notifier $notifier */
	protected $notifier;
	/** @var Utilities $utilities */
	protected $utilities;

	/**
	 * Audit_Core_Code_Scan constructor.
	 *
	 * @param $notifier
	 * @param $utilities
	 */
	public function __construct( $notifier, $utilities ) {
		$this->notifier  = $notifier;
		$this->utilities = $utilities;
		add_action( 'FULLWORKS_VULNERABILITY_SCANNER_email_check_audit_complete', array( $this, 'check_audit_complete' ) );
		add_action( 'FULLWORKS_VULNERABILITY_SCANNER_send_email', array( $this, 'send_email' ) );
	}


	public function run() {
		// simply queue 10 minutes later to make sure other jobs have started
		if ( false === as_next_scheduled_action( 'FULLWORKS_VULNERABILITY_SCANNER_email_check_audit_complete', array(), 'fullworks-vulnerability-scanner-control' ) ) {
			as_schedule_single_action( time() + 600, 'FULLWORKS_VULNERABILITY_SCANNER_email_check_audit_complete', array(), 'fullworks-vulnerability-scanner-control' );
		}
	}


	public function check_audit_complete() {
		if ( false == Audit_Action_Scheduler::check_group_complete(
				array(
					'FULLWORKS_VULNERABILITY_SCANNER_audit'
				),
				'FULLWORKS_VULNERABILITY_SCANNER_email_check_audit_complete' ) ) {
			return;
		}
		$this->send_email();
	}

	/**
	 *
	 */
	public function send_email() {

		/** @var $wpdb /wpdb */
		global $wpdb;

		$critical = $wpdb->get_var( "SELECT COUNT(*) FROM {$wpdb->prefix}fwvs_file_audit WHERE `accept` = 0  AND status > 500" );

		$warning = $wpdb->get_var( "SELECT COUNT(*) FROM {$wpdb->prefix}fwvs_file_audit WHERE `accept` = 0  AND status <= 500" );
		if ( ( $critical + $warning ) < 1 ) {  // no unaccepted issues
			return;
		}
		$options = get_option( 'fullworks-vulnerability-scanner-audit-schedule' );
		if ( ! isset( $options['email'] ) || true != $options['email']['warning'] ) {
			if ( ( $critical ) < 1 ) {  // no unaccepted critical issues
				return;
			}
		}
		$subject   = sprintf(
			// translators: placeholder 1 is plugin title and  2 is site name
			esc_html__( '[%1$s]: Issues found during code scan of %2$s', 'fullworks-vulnerability-scanner' ),
			$this->utilities->get_plugin_title(),
			get_bloginfo( 'name' )
		);
		$variables = array(
			'{url}'          => get_bloginfo( 'wpurl' ),
			'{sitename}'     => get_bloginfo( 'name' ),
			'{target}'       => get_admin_url( null, 'admin.php?page=fullworks-vulnerability-scanner-code-scan-report' ),
			'{date_time}'    => gmdate( 'l jS \of F Y h:i:s A' ),
			'{critical}'     => $critical,
			'{warning}'      => $warning,
			'{plugin_title}' => $this->utilities->get_plugin_title()
		);

		// translators: items in {} are placeholder - do not translate items inside {} e.g. {name}
		$message = esc_html__( "Hi Administrator of {sitename},
		
Date: {date_time}

The vulnerability scan of {sitename} has completed

Issue Summary

Number of critical issues: {critical}
Number of warnings: {warning}

Review these issues to resolve or accept them at: {target}

  
This message was generated by {plugin_title}
	 
		 ", 'fullworks-vulnerability-scanner' );

		$message = strtr( $message, $variables );
		$this->notifier->notify( __FUNCTION__, $subject, $message, 'admin' );
	}
}

